FROM xebialabsunsupported/xl-deploy:8.5.0-alpha.25-no-devops-as-code

COPY default-conf/deployit-license.lic /opt/xebialabs/xl-deploy-server/default-conf/
COPY lib/* /opt/xebialabs/xl-deploy-server/lib/
