FROM xebialabsunsupported/xl-release:8.5.0-alpha.22-no-devops-as-code

COPY default-conf/xl-release-license.lic /opt/xebialabs/xl-release-server/default-conf/
COPY lib/* /opt/xebialabs/xl-release-server/lib/
